import * as fs from 'fs';

export const bingCookie = fs.readFileSync('./src/bingCookie.txt', 'utf8');

export const messageInfo = {
    // locale: 'en-US',
    // market: 'en-US',
    // region: 'US',
    // location: 'lat:47.639557;long:-122.128159;re=1000m;',
    // locationHints: [
    //     {
    //         SourceType: 1,
    //         RegionType: 2,
    //         Center: {
    //             Latitude: 37.75870132446289,
    //             Longitude: -122.4811019897461,
    //         },
    //         Radius: 24902,
    //         Name: 'San Francisco, California',
    //         Accuracy: 24902,
    //         FDConfidence: 0.8999999761581421,
    //         CountryName: 'United States',
    //         CountryConfidence: 9,
    //         Admin1Name: 'California',
    //         PopulatedPlaceName: 'San Francisco',
    //         PopulatedPlaceConfidence: 9,
    //         PostCodeName: '94122',
    //         UtcOffset: -8,
    //         Dma: 807,
    //     },
    // ],
    // userIpAddress: '135.180.64.190',
    // timestamp: '2024-03-14T06:42:40-07:00',
};

export const newConversationHeaders = {
    accept: 'application/json',
    'accept-language': 'en-US,en;q=0.9',
    'content-type': 'application/json',
    'sec-ch-ua':
        '"Microsoft Edge";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
    'sec-ch-ua-arch': '"x86"',
    'sec-ch-ua-bitness': '"64"',
    'sec-ch-ua-full-version': '"113.0.1774.50"',
    'sec-ch-ua-full-version-list':
        '"Microsoft Edge";v="113.0.1774.50", "Chromium";v="113.0.5672.127", "Not-A.Brand";v="24.0.0.0"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-model': '""',
    'sec-ch-ua-platform': '"Windows"',
    'sec-ch-ua-platform-version': '"15.0.0"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'sec-ms-gec-version': '1-115.0.1866.1',
    'x-ms-useragent':
        'azsdk-js-api-client-factory/1.0.0-beta.1 core-rest-pipeline/1.10.0 OS/Win32',
    'user-agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.50',
    Referer: 'https://www.bing.com/search?q=Bing+AI&showconv=1',
    'Referrer-Policy': 'origin-when-cross-origin',
};

export const requestOptions = (saveMem = false, imageGen = false) => ({
    source: 'cib-ccp',
    optionsSets: [
        'nlu_direct_response_filter',
        // 'enable_debug_commands',
        'deepleo',
        'disable_emoji_spoken_text',
        'responsible_ai_policy_235',
        'enablemm',
        'dv3sugg',
        // 'autosave',
        'iyxapbing',
        'iycapbing',
        'h3imaginative',
        'jb204cftr085',
        'hourthrot',
        'gndlogcf',
        'vidtoppb',
        'eredirecturl',
        'clgalileo',
        ...imageGen ? ['gencontentv3'] : [],
        'enable_user_consent',
        'fluxmemcst',
        ...saveMem ? ['autosave'] : [],
    ],
    allowedMessageTypes: [
        'ActionRequest',
        'Chat',
        'ConfirmationCard',
        'Context',
        'InternalSearchQuery',
        'InternalSearchResult',
        'Disengaged',
        'InternalLoaderMessage',
        'Progress',
        'RenderCardRequest',
        'RenderContentRequest',
        'AdsQuery',
        'SemanticSerp',
        'GenerateContentQuery',
        'SearchQuery',
        'GeneratedCode',
        'InternalTasksMessage',
    ],
    sliceIds: [
        'bgstreamcf',
        'rwt2',
        'scmcbasecf',
        'cmcpupsalltf',
        'thdnsrch',
        'sunoupsellcf',
        '0215wcrwip',
        '301jb204cf',
        '0312hrthrot',
        'bingfc',
        '0225unsticky1',
        'dissagrds0',
        '308videopb',
        '3022tphpv',
    ],
    verbosity: 'verbose',
    scenario: 'SERP',
    plugins: [
        { id: 'c310c353-b9f0-4d76-ab0d-1dd5e979cf68', category: 1 },
    ],
    conversationHistoryOptionsSets: [
        ...saveMem ? ['autosave'] : [],
        'savemem',
        'uprofupd',
        'uprofgen',
    ],
    gptId: 'copilot', // wtf does this do?
});
